### ISSUE TITLE
Battery Availability Status

### ISSUE THREAD

**Issue by snkaupe** [Sapd/HeadsetControl#102]
As of now, HeadsetControl is unable to differentiate between a battery charging and the headset (and therefore its battery) not being connected. This results in an erroneous battery status  output ("Charging") when querying the battery level of a disconnected device.

Example:
```bash
# Device is connected but not loading:
$ headsetcontrol -b
Found Corsair Void (Pro)!

Battery: 97%
# Device is now disconnected/turned off:
$ headsetcontrol -b
Found Corsair Void (Pro)!

Battery: Charging # <- This is obviously incorrect and should state something like "Unavailable".
```

For the Corsair VOID PRO Wireless headset, this is easily resolved by checking the last byte of the battery status answer, which is `0` when the headset is disconnected (see also the implementation of battery level requests [in Perif](https://github.com/olback/perif/blob/master/libperif/src/devices/corsair/void.rs#L35), a similar tool which gave me this idea. Thanks to olback for finding this). I have created [a PR](https://github.com/Sapd/HeadsetControl/pull/101) implementing this. 

However, I do not have access to any other headset supported by HeadsetControl and are therefore unable to implement something similar for them. It would be lovely if somebody could drop in and check if this would also be possible for other devices. As it is, the proposed PR should not negatively impact said other devices.

**Comment by Sapd** [comment]
Thank you, closed as corresponding PR merged.
