### ISSUE TITLE
Doesn't detect on arch

### ISSUE THREAD

**Issue by headassbtw** [Sapd/HeadsetControl#119]
Recently reinstalled arch(manjaro) and noticed that the program can't find my headset anymore. it's a corsair void elite RGB wireless (which IS supported), but the program can't find it. it shows under lsusb as well, not sure what the problem is.
any help i can give or get is welcome
![image](https://user-images.githubusercontent.com/16214950/102271972-e91e5480-3ed4-11eb-9057-22f6a4e91017.png)

**Comment by Sapd** [comment]
hmm maybe you pulled an old version. I just checked and the id of your headset is in the source code.

How did you install HeadsetControl?

**Comment by headassbtw** [comment]
um, pamac, my graphical package manger of choice, was that the problem? do i need to compile from source?

**Comment by parkerlreed** [comment]
Install headsetcontrol-git from AUR

**Comment by headassbtw** [comment]
sick, that worked, thank you!
