### ISSUE TITLE
Can't compile using latest Cmake (3.19.2-1)

### ISSUE THREAD

**Issue by vscsilva** [Sapd/HeadsetControl#124]
![Captura de tela de 2020-12-31 07-33-09](https://user-images.githubusercontent.com/64592232/103406760-95e60c00-4b3a-11eb-9b35-9ceeee34ed9e.png)

**Comment by Sapd** [comment]
Is the *make* package installed?

**Comment by vitor180396** [comment]
> Is the _make_ package installed?

Yes
![image](https://user-images.githubusercontent.com/64592232/103446661-01c29480-4c61-11eb-83e0-de629ee9bb64.png)

**Comment by core1024** [comment]
You're obviously using Arch Linux based distro. Have you tried installing it from AUR? Or at least check the PKGBUILD. There are listed all the dependencies you need. If you have `yay` installed you only need to issue `yay -S headsetcontrol-git` as normal user.

**Comment by vitor180396** [comment]
> 
> 
> You're obviously using Arch Linux based distro. Have you tried installing it from AUR? Or at least check the PKGBUILD. There are listed all the dependencies you need. If you have `yay` installed you only need to issue `yay -S headsetcontrol-git` as normal user.

That worked but still curious why I got this error. I was able to compile before without any issues.

**Comment by Sapd** [comment]
The error arises, as it simply cant find make in the path. You can try typing `where make` to see if it is in the PATH. If not, cmake cant find it either.

**Comment by vitor180396** [comment]
> The error arises, as it simply cant find make in the path. You can try typing `where make` to see if it is in the PATH. If not, cmake cant find it either.

![image](https://user-images.githubusercontent.com/64592232/103490310-c8715c80-4df9-11eb-95a4-e8569ac1674f.png)

**Comment by vscsilva** [comment]
You can close this.

**Comment by parkerlreed** [comment]
What was it? (Since you are the author you can close this yourself as well)

**Comment by vscsilva** [comment]
If I remember correctly that was due to missing `g++`
