### ISSUE TITLE
Arctic 5

### ISSUE THREAD

**Issue by JokerGermany** [Sapd/HeadsetControl#134]
Hi, 
it would be great if you can add support for the Arctic 5.
I want to put off the Light, because i am not a christmas tree.

If you need any infos, i will help.

Thanks.

**Comment by t1nux** [comment]
seconded, but for being able to use sidetone

**Comment by sonalder-darlene** [comment]
I've tried to make a profile with a friend who is a more advanced programmer and we didn't figure out some errors.
So we couldn't make it to work sadly...

**Comment by t1nux** [comment]
You can control side-tone through alsamixer. This was the main feature for me, so I'm currently happy with this approach.

**Comment by Shoryureppa01** [comment]
Adding my $0.02 to also request support
