### ISSUE TITLE
G935 Light strips won't turn off

### ISSUE THREAD

**Issue by F0x06** [Sapd/HeadsetControl#135]
Version: ef39a18037fab8fa31190de1229fa7c5afd5cf77
OS: ArchLinux (Manjaro), 5.10.2-2-MANJARO

Hi, when running `sudo headsetcontrol -l 0` only the logo lights turns off, but the light strips stays on, tested this on windows and it works, but the behavior is inverted, on windows logo stay on and strips off

PS: I spammed the command like 5-7 times and now the strips went off

Thanks.

**Comment by Cr7mbl3** [comment]
Same here
