### ISSUE TITLE
G533 macOS High Sierra (10.13.4)

### ISSUE THREAD

**Issue by codmpm** [Sapd/HeadsetControl#15]
Thank you for this!! I've already asked the Logitech support a thousand times for OSX support for the Gaming-Headsets. Besides gaming on a Win10 machine I'm also using the headset unser OSX.

Now for the problem: I'm using a G533 and can't set the sidetone like it should be: 

`./HeadsetControl -s 128` disables sidetone completely, which is ok for me.
`./HeadsetControl -s 127` and `./HeadsetControl -s 1` practicaly have the same loudness on sidetone (very loud), can't tell any difference.

I've cloned the current `master` and compiled it with make, cmake, etc. via brew.

The problem ist not, that I'm missing the sidetone but that I hear a loud swooshy noise (Rauschen) obviously coming from the sidetone if enabled. Under Windows I can get around this by setting the sidetone to ~50%. 

So on OSX currently `-s 128` is working for me without any sidetone at all.
Is this is a bug or did I understand something wrong?

Cheers and thank you,
Patrik

**Comment by Sapd** [comment]
No, normally 128 should be the highest level and 0 no sidetone.

The G533 supported was created by simply adapting the Corsair VOID solution, as it was the same protocol.

I looked into the history and It seems like I omitted a mapping of the values, when I adapted to a new software structure.
Can you try go into _src/devices_ open _logitech_g533.c_ and insert before line 25 (directly after the start of the function) `num = map(num, 0, 128, 200, 255);` and on top of the file `#include "../utility.h"`?

**Comment by codmpm** [comment]
Worked like a charm, thank you. 

But there seems something wrong with the info given, if I use `-s 129`: 

    Usage: ./HeadsetControl -s 0-100

**Comment by Sapd** [comment]
Thank you, I updated Master.

**Comment by codmpm** [comment]
Especially thank you!
