### ISSUE TITLE
Logitech G733 Gaming Headset - not recognized

### ISSUE THREAD

**Issue by hselasky** [Sapd/HeadsetControl#152]
usbconfig -d ugen0.5 dump_device_desc
ugen0.5: <Logitech G733 Gaming Headset> at usbus0, cfg=0 md=HOST spd=FULL (12Mbps) pwr=ON (100mA)

  bLength = 0x0012 
  bDescriptorType = 0x0001 
  bcdUSB = 0x0110 
  bDeviceClass = 0x0000  <Probed by interface class>
  bDeviceSubClass = 0x0000 
  bDeviceProtocol = 0x0000 
  bMaxPacketSize0 = 0x0040 
  idVendor = 0x046d 
  idProduct = 0x0ab5 
  bcdDevice = 0x0100 
  iManufacturer = 0x0003  <Logitech>
  iProduct = 0x0004  <G733 Gaming Headset>
  iSerialNumber = 0x0000  <no string>
  bNumConfigurations = 0x0001

**Comment by DanyGee** [comment]
Did you try running `headsetcontrol` as root?

**Comment by hselasky** [comment]
Yes, the USB ID's are missing in there.

**Comment by Sapd** [comment]
The most recent version should have the ID included

**Comment by hselasky** [comment]
Thank you! Works as expected!
