### ISSUE TITLE
Corsair HS70 BLUETOOTH Error: -1 (null)

### ISSUE THREAD

**Issue by Kharonus** [Sapd/HeadsetControl#158]
Ahoi,
already looked to some of the other issue. Apparently HS70 works fine for most users, after maybe having some starting problems.

my system: ubuntu 20.04
my headset (from lsusb): `Bus 001 Device 006: ID 1b1c:0a61 Corsair HS70 BLUETOOTH Gaming Headset`

What goes wrong on my side:
```
> headsetcontrol -b
Found Corsair Headset Device!

Failed to request battery. Error: -1: (null)
```

same goes for setting sidetone, playing notification, etc.

I added the device id like written in corsair HOWTO to the corsair_void.c, run `make` and `make install`.

Do you by chance have a clue, what I'm missing?

**Comment by Sapd** [comment]
Probably same protocol/problem like: https://github.com/Sapd/HeadsetControl/issues/178

**Comment by bnjns** [comment]
I've got both the HS70 and HS80 so can give the 70 a try too
