### ISSUE TITLE
G733 only turns off bottom light

### ISSUE THREAD

**Issue by heismauri** [Sapd/HeadsetControl#173]
Hello there my device is detected as `Found Logitech G633/G635/G933/G935!` and everytime I run the command `headsetcontrol -l 0`it only turns off the bottom light. I am currently on MacOS Catalina.

**Comment by ShreyamMaity** [comment]
> Hello there my device is detected as `Found Logitech G633/G635/G933/G935!` and everytime I run the command `headsetcontrol -l 0`it only turns off the bottom light. I am currently on MacOS Catalina.

try `headsetcontrol -l 0 0` to turn off both and `headsetcontrol -l 1 1`  to turn on both ;)
