### ISSUE TITLE
gentoo mirror nitratesky is using the old version 2.3

### ISSUE THREAD

**Issue by HashimHL** [Sapd/HeadsetControl#190]
Hello,

I have had issues with installing headsetcontrol via [nitratesky](https://github.com/gentoo-mirror/nitratesky#app-mischeadsetcontrol) since the version is older (2.3) and the current documentation does not match it (2.5).  

after cloning and compiling from source everything worked well.

**Comment by Sapd** [comment]
You probably need to open up an issue at @VTimofeenko 's repository

**Comment by HashimHL** [comment]
Got it, thank you @Sapd

**Comment by VTimofeenko** [comment]
Thanks for the ping, bumped the version to 2.6
