### ISSUE TITLE
`-?` option incompatible with Zsh

### ISSUE THREAD

**Issue by MicaelJarniac** [Sapd/HeadsetControl#204]
### Description

```
➜  ~ headsetcontrol   
Found Logitech G533!
You didn't set any arguments, so nothing happened.
Type headsetcontrol -h for help.
➜  ~ headsetcontrol -?
zsh: no matches found: -?
```

Operating System: Manjaro Linux
KDE Plasma Version: 5.24.2
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.15.25-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × AMD Ryzen 3 2200G with Radeon Vega Graphics
Memory: 7.7 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 970/PCIe/SSE2

### On which OS does the problem happen?

Linux

**Comment by MicaelJarniac** [comment]
I'd say this is a very tiny minor issue because there's still the `--capabilities`, which does work perfectly.

**Comment by Sapd** [comment]
It is the globbing of ZSH and perfectly normal.

You can either wrap it in `"` or `'`, use a backslash before the `?` or use `setopt noglob`
