### ISSUE TITLE
HeadsetControl Corsair HS80 can't turn off RGB light

### ISSUE THREAD

**Issue by escbooster12** [Sapd/HeadsetControl#206]
### Description

I just bought yesterday Corsair HS80, I initially turn off the RGB of the headset because for me its useless and waste of battery. All were working fine in my Windows by the help of iCue Sofware. Now the problem is when I shift in my Ubuntu, I thought the preferences would just easily be saved. but I was wrong. I have no total control of the RGB in Ubuntu. So I researched and discovered _"headsetControl"_

Have followed instructions and finished the setup [_Adding a Corsair device_](https://github.com/Sapd/HeadsetControl/wiki/Adding-a-Corsair-device). 
<details> <summary> show configuration </summary> 

```
#define ID_CORSAIR_VOID_WIRELESS           0x1b27
#define ID_CORSAIR_VOID_PRO                0x0a14
#define ID_CORSAIR_VOID_PRO_R2             0x0a16
#define ID_CORSAIR_VOID_PRO_USB            0x0a17
#define ID_CORSAIR_VOID_PRO_WIRELESS       0x0a1a
#define ID_CORSAIR_VOID_RGB_USB            0x1b2a
#define ID_CORSAIR_VOID_RGB_USB_2          0x1b23
#define ID_CORSAIR_VOID_RGB_WIRED          0x1b1c
#define ID_CORSAIR_VOID_ELITE_WIRELESS     0x0a55
#define ID_CORSAIR_VOID_RGB_ELITE_WIRELESS 0x0a51
#define ID_CORSAIR_VOID_ELITE_USB          0x0a52
#define ID_CORSAIR_HS70_WIRELESS           0x0a38
#define ID_CORSAIR_HS70_PRO                0x0a4f
#define ID_CORSAIR_VOID_RGB_WIRELESS       0x0a2b
#define ID_CORSAIR_HS80_RGB_WIRELESS       0x0a6b

static const uint16_t PRODUCT_IDS[] = {
    ID_CORSAIR_VOID_RGB_WIRED,
    ID_CORSAIR_VOID_WIRELESS,
    ID_CORSAIR_VOID_PRO,
    ID_CORSAIR_VOID_PRO_R2,
    ID_CORSAIR_VOID_PRO_USB,
    ID_CORSAIR_VOID_PRO_WIRELESS,
    ID_CORSAIR_VOID_RGB_USB,
    ID_CORSAIR_VOID_RGB_USB_2,
    ID_CORSAIR_VOID_ELITE_WIRELESS,
    ID_CORSAIR_VOID_RGB_ELITE_WIRELESS,
    ID_CORSAIR_VOID_ELITE_USB,
    ID_CORSAIR_HS70_WIRELESS,
    ID_CORSAIR_HS70_PRO,
    ID_CORSAIR_VOID_RGB_WIRELESS,
    ID_CORSAIR_HS80_RGB_WIRELESS,
};

```

 </details>

I tried the command `headsetcontrol -l 0` and it showed _Success!_, but there are no changes, RGB light is still on.
I want to ask assistance maybe you guys can help me out. 

![image](https://user-images.githubusercontent.com/54020235/163407089-fd2d6196-4c7b-4603-9dae-98f74feda1cd.png)

### Headset Name

Corsair HS80

### On which OS does the problem happen?

Linux

### Device information

<details>
 <summary>Detailed Device Information</summary>

when i ran `headsetcontrol --dev -- --list` there were two info showed related to _Corsair hs80_ but has the same `ProductId` and `VendorId`

 ```
VendorID: 0x1b1c
 ProductID: 0x0a6b
  path: /dev/hidraw1
  serial_number: 16cec6c300010215
  Manufacturer: Corsair
  Product:      CORSAIR HS80 RGB Wireless Gaming Receiver
  Interface:    3
  Usage-Page: 0x0 Usageid: 0x0

Device Found
  VendorID: 0x1b1c
 ProductID: 0x0a6b
  path: /dev/hidraw2
  serial_number: 16cec6c300010215
  Manufacturer: Corsair
  Product:      CORSAIR HS80 RGB Wireless Gaming Receiver
  Interface:    4
  Usage-Page: 0x0 Usageid: 0x0

 ```

</details>

**Comment by Sapd** [comment]
Unfortunately the HS80 works quite differently.

So you would have to use WireShark to analyze the packets.

Actually there is a big thread here: https://github.com/Sapd/HeadsetControl/issues/178
