### ISSUE TITLE
Build issue 

### ISSUE THREAD

**Issue by IReficul** [Sapd/HeadsetControl#219]
When building on openSUSE Tumbleweed x86_64 

Issue seems to be similar to: https://github.com/darlinghq/darling/issues/889

My build fails with:

-- The C compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/reficul/Desktop/Apps/HeadsetControl/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_d7579/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_d7579.dir/build.make CMakeFiles/cmTC_d7579.dir/build
    gmake[1]: Entering directory '/home/reficul/Desktop/Apps/HeadsetControl/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_d7579.dir/testCCompiler.c.o
    /usr/bin/cc    -o CMakeFiles/cmTC_d7579.dir/testCCompiler.c.o -c /home/reficul/Desktop/Apps/HeadsetControl/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_d7579
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d7579.dir/link.txt --verbose=1
    /usr/bin/cc CMakeFiles/cmTC_d7579.dir/testCCompiler.c.o -o cmTC_d7579 
    /usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: i386 architecture of input file `/lib/crt1.o' is incompatible with i386:x86-64 output
    /usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: i386 architecture of input file `/lib/crti.o' is incompatible with i386:x86-64 output
    /usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: i386 architecture of input file `/lib/crtn.o' is incompatible with i386:x86-64 output
    /usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: /lib/crt1.o: file class ELFCLASS32 incompatible with ELFCLASS64
    /usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: loppulinkitys ei onnistunut: file in wrong format
    collect2: error: ld returned 1 exit status
    gmake[1]: *** [CMakeFiles/cmTC_d7579.dir/build.make:99: cmTC_d7579] Error 1
    gmake[1]: Leaving directory '/home/reficul/Desktop/Apps/HeadsetControl/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_d7579/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!

**Comment by Sapd** [comment]
A bit late, but try `apt install build-essential` maybe even with the `--reinstall` option

**Comment by IReficul** [comment]
I was able to compile and install it somehow.
