### ISSUE TITLE
Sidetone Disables After Sound Sometimes (G430)

### ISSUE THREAD

**Issue by fotsss** [Sapd/HeadsetControl#22]
Hello,

I built HeadsetControl on MacOS for my g430s using build 41be993 and everything seems to work well besides one issue: The sidetone setting seems to reset; specifically after a new sound is made.

For instance, after setting "headsetcontrol -s 0" it will silence sidetone, but if I were to play a youtube video, it would reset. If I were to set "headsetcontrol -s 0" again, it would work for the remainder of the youtube video, then loading a new page, playing music, etc. will trigger it to reset again. I'm aware I can setup a loop like "while sleep 1; do HeadsetControl -s 0; done", but is there a more permanent solution available?

Any help would be much appreciated, Thank you for this build.

**Comment by Sapd** [comment]
That behavior is somehow weird. Doesn't it happen on Windows?

Fixing it would require new analysis from people who own the G430.
