### ISSUE TITLE
Having trouble following documentation for "Adding a device"

### ISSUE THREAD

**Issue by sesu-tech** [Sapd/HeadsetControl#226]
I have a Corsair Virtuoso Non-SE and I'm really eager to get at least the sidetone working, that's pretty big for me at least.

I was following the documentation, compiled HeadsetControl, and I got to step 1 of "Adding the deviceid to the implementation".
For 2, I don't understand what it means by "array PRODUCT_IDS", is this a file or a section of some file in the build that I'm not seeing?
![Screenshot_20220813_220215](https://user-images.githubusercontent.com/25572885/184519496-264aa90e-0171-49e6-bb46-847296830e49.png)

Side-note: I'm willing to support this project in adding support for my Virtuoso - I'm not too skilled in this area specifically, but have done a bit of programming and scripting myself. And at the very least, I actually HAVE this device, so I'm free to supply any device information I can get from the command-line if need be. :)

**Comment by Sapd** [comment]
Corsair Virtuso might be much more difficult:
https://github.com/Sapd/HeadsetControl/issues/71

Sidetone is controllable via Alsamixer, for battery someone would need to use wireshark to capture the packets
