### ISSUE TITLE
Logitech G PRO X Wireless

### ISSUE THREAD

**Issue by ubarilan** [Sapd/HeadsetControl#239]
### Description

Hello,
In the README.md file Logitech G PRO is specified but I'm not sure if it also means the Logitech G PRO X Wireless is supported as well, if not, can you please add support for that model?

Thanks!

### Headset Name

Logitech G PRO X Wireless

### Device information

<details>
 <summary>Detailed Device Information</summary>

 ```
I don't currently have the device, but want to buy it soon
 ```

</details>

**Comment by Bananaman** [comment]
Yes you can dig a bit more in this project and you would see that the PRO X Wireless is supported.

For example:

https://github.com/Sapd/HeadsetControl/pull/197/files
