### ISSUE TITLE
Refer to Logitech docs when possible

### ISSUE THREAD

**Issue by hadess** [Sapd/HeadsetControl#243]
### Description

Logitech has some data about HID++ devices available at:
https://drive.google.com/drive/folders/0BxbRzx7vEV7eWmgwazJ3NUFfQ28

including:
- `x8300_sidetoneadjustment_v1.pdf` for the sidetone support
- `240 mAh battery - soc conversion table.txt` for the battery info for some G Pro devices
- `logitech_hidpp_2.0_specification_draft_2012-06-04.pdf` for most other Logitech HID++ devices
- `Logitech_hidpp10_specification_draft_for_unifying_receivers.docx` for HID++ 1.0 devices
- `x1982_backlight_v2.pdf` might be used for headset lights
- `x8310_audioeq_v2.pdf` might be useful for more audio control

It would be useful to refer to the docs when they exist, so that reverse engineered values aren't mixed in with documented ones.

### On which OS does the problem happen?

Linux

**Comment by Sapd** [comment]
It is done a bit in `src/devices/logitech.h` where all constants and information regarding the protocols should reside. But me myself I cannot really help here any further as I currently don't use a Logitech Headset for verification. Feel free to create a PR or WIP PR as always.
