### ISSUE TITLE
Settings clear after headset reset

### ISSUE THREAD

**Issue by GoodMew** [Sapd/HeadsetControl#301]
### Description

I'm making an assumption that this isn't normal. Every time I turn my headset off and on again, all settings go back to default. So I have to turn off the LEDs and adjust the sidetone again. 

In the GNOME shell extension, I've added the settings I want like -l 0 and -s 60 but they are not implemented. Setting them through terminal works fine, but still, they are set back to default when I reset. I am new to Linux, using Fedora with G733 headset.

### On which OS does the problem happen?

Linux

**Comment by Sapd** [comment]
Its normal. The headsets don't have a memory where settings could be saved.

So that means scripts calling headsetcontrol need to remember the settings. Basically you should open up an issue in the repository of the shell extension you are using
