### ISSUE TITLE
Feature request: get current sidetone level with -s

### ISSUE THREAD

**Issue by snosratiershad** [Sapd/HeadsetControl#313]
### Description

When -s option called with no parameter, I expect that to show the current level of sidetone.

**Comment by Sapd** [comment]
Not really possible. The program is stateless, it would need to retrieve it from the headset (which might be again not possible).
If you write a script around headsetcontrol, that script needs to save the latest state.

**Comment by snosratiershad** [comment]
@Sapd Thanks for your response. I'm also on the same page with keeping the program stateless,if it's not possible to retrieve it from headset, I think we should close this issue.
