### ISSUE TITLE
Add option to check if headset is connected

### ISSUE THREAD

**Issue by AinoSpring** [Sapd/HeadsetControl#322]
### Description

When writing scripts using headsetcontrol, it would be very practical having
a flag which checks if there is a headset connected.

**Comment by Sapd** [comment]
Will be provided indirectly over 
https://github.com/Sapd/HeadsetControl/issues/271
(Feel free to comment there for feedback)

**Comment by AinoSpring** [comment]
Yeah but when writing stuff like bash scripts (e. g. for an i3 status bar module) it
would be really convenient if you could do something like

`if [ headsetcontrol --connected ] ; then`

and it feels like it should exist.

**Comment by Sapd** [comment]
Makes sense, will probably implement that and --count or so to check how many are connected (used for further use cases).
