### ISSUE TITLE
Incorrect ChatMix help message

### ISSUE THREAD

**Issue by TheBill2001** [Sapd/HeadsetControl#341]
### Description

Currently, the help message for ChatMix indicates the argument accepts a value.
```
  -m, --chatmix LEVEL           Get chat-mix-dial level (0-128, <64 for game, >64 for chat)
```

Wouldn't it be this instead?
```
  -m, --chatmix                 Get chat-mix-dial level (0-128, <64 for game, >64 for chat)
```

### On which OS does the problem happen?

Linux

**Comment by Sapd** [comment]
Yep good catch, will have to fix it
