### ISSUE TITLE
Integrate with D-Bus / Upower

### ISSUE THREAD

**Issue by qdrop17** [Sapd/HeadsetControl#343]
### Description

First of all, I highly appreciate this software. It enables me to look more professional in meetings and a bit more geeky while gaming. ;-)

This software accurately enumerates the battery level of my G733:

```
$ headsetcontrol -b
Found Logitech G633/G635/G733/G933/G935!
Battery: 94%
Success!
```

What do you think about integrating this capability with https://upower.freedesktop.org/docs/Device.html? This would bring together the battery state of all my peripherals in one central place, including notifications when the battery gets low:

![image](https://github.com/Sapd/HeadsetControl/assets/42340241/b48a2219-3686-43db-a193-5cbb5b8f5890)

Would this be complicated to implement? I would also be happy to help with testing.

**Comment by Sapd** [comment]
Its quite an specific feature.

I think the best way would be not to implement it directly in HeadsetControl, but to write a program or a simple script with SystemD Daemon which will call HeadsetControl and then forward it to DBus. Would then also fit the UNIX principle
