### ISSUE TITLE
Steelseries Artic 7 2019 not reconnized

### ISSUE THREAD

**Issue by olielvewen** [Sapd/HeadsetControl#35]
Hi,
I've purchased for Christmas an Steelseries Headset Artic 7 version 2019 and it is not reconnized on Linux Manjaro with the last version of HeadsetControl.
<code>[olivier@thorielle ~]$ HeadsetControl -h
Headsetcontrol written by Sapd (Denis Arnst)
        https://github.com/Sapd

Parameters
  -s level      Sets sidetone, level must be between 0 and 128
  -b            Checks the battery level
  -n soundid    Makes the headset play a notifiation

[olivier@thorielle ~]$ HeadsetControl -b
Headsetcontrol written by Sapd (Denis Arnst)
        https://github.com/Sapd

No supported headset found
[olivier@thorielle ~]$ HeadsetControl -n 0
Headsetcontrol written by Sapd (Denis Arnst)
        https://github.com/Sapd

No supported headset found</code>

Here more explanation about my system and usb:

<code>[olivier@thorielle ~]$ lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 046d:c517 Logitech, Inc. LX710 Cordless Desktop Laser
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 1b1c:1b51 Corsair 
Bus 001 Device 003: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 002: ID 1038:12ad SteelSeries ApS 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

<code>
[olivier@thorielle ~]$ dmesg | grep usb
[    0.718696] usbcore: registered new interface driver usbfs
[    0.718696] usbcore: registered new interface driver hub
[    0.718700] usbcore: registered new device driver usb
[    0.869704] usbcore: registered new interface driver usbserial_generic
[    0.869708] usbserial: USB Serial support registered for generic
[    1.718711] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.19
[    1.718712] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.718713] usb usb1: Product: xHCI Host Controller
[    1.718714] usb usb1: Manufacturer: Linux 4.19.12-2-MANJARO xhci-hcd
[    1.718714] usb usb1: SerialNumber: 0000:02:00.0
[    1.719509] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[    1.719522] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 4.19
[    1.719523] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.719524] usb usb2: Product: xHCI Host Controller
[    1.719524] usb usb2: Manufacturer: Linux 4.19.12-2-MANJARO xhci-hcd
[    1.719525] usb usb2: SerialNumber: 0000:02:00.0
[    1.720267] usb usb3: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.19
[    1.720268] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.720268] usb usb3: Product: xHCI Host Controller
[    1.720269] usb usb3: Manufacturer: Linux 4.19.12-2-MANJARO xhci-hcd
[    1.720270] usb usb3: SerialNumber: 0000:0a:00.3
[    1.720467] usb usb4: We don't know the algorithms for LPM for this host, disabling LPM.
[    1.720480] usb usb4: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 4.19
[    1.720481] usb usb4: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.720481] usb usb4: Product: xHCI Host Controller
[    1.720482] usb usb4: Manufacturer: Linux 4.19.12-2-MANJARO xhci-hcd
[    1.720483] usb usb4: SerialNumber: 0000:0a:00.3
[    2.046734] usb 1-2: new full-speed USB device number 2 using xhci_hcd
[    2.050041] usb 3-2: new full-speed USB device number 2 using xhci_hcd
[    2.224527] usb 3-2: New USB device found, idVendor=046d, idProduct=0b02, bcdDevice=40.02
[    2.224530] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.224531] usb 3-2: Product: Logitech BT Mini-Receiver
[    2.224532] usb 3-2: Manufacturer: Logitech
[    2.360881] usb 1-2: New USB device found, idVendor=1038, idProduct=12ad, bcdDevice= 1.19
[    2.360884] usb 1-2: New USB device strings: Mfr=4, Product=5, SerialNumber=0
[    2.360885] usb 1-2: Product: SteelSeries Arctis 7
[    2.360886] usb 1-2: Manufacturer: SteelSeries 
[    2.433491] usbcore: registered new interface driver usbhid
[    2.433493] usbhid: USB HID core driver
[    2.435318] input: SteelSeries  SteelSeries Arctis 7 Consumer Control as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-2/1-2:1.5/0003:1038:12AD.0001/input/input2
[    2.490070] input: SteelSeries  SteelSeries Arctis 7 as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-2/1-2:1.5/0003:1038:12AD.0001/input/input4
[    2.490454] hid-generic 0003:1038:12AD.0001: input,hiddev0,hidraw0: USB HID v1.11 Device [SteelSeries  SteelSeries Arctis 7] on usb-0000:02:00.0-2/input5
[    2.513369] usb 1-6: new full-speed USB device number 3 using xhci_hcd
[    2.670414] usb 3-2.2: new full-speed USB device number 3 using xhci_hcd
[    2.807549] usb 3-2.2: New USB device found, idVendor=046d, idProduct=c70e, bcdDevice=40.02
[    2.807552] usb 3-2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.807554] usb 3-2.2: Product: Logitech BT Mini-Receiver
[    2.807555] usb 3-2.2: Manufacturer: Logitech
[    2.807556] usb 3-2.2: SerialNumber: 000761A35EDF
[    2.843012] usb 1-6: New USB device found, idVendor=1b1c, idProduct=1b51, bcdDevice= 3.08
[    2.843014] usb 1-6: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.843016] usb 1-6: Product: CORSAIR DARK CORE RGB SE Wireless USB Receiver
[    2.843017] usb 1-6: Manufacturer: Corsair
[    2.843018] usb 1-6: SerialNumber: 16007025AF099D2258CCD846F5001946
[    2.872108] input: Corsair CORSAIR DARK CORE RGB SE Wireless USB Receiver Mouse as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-6/1-6:1.0/0003:1B1C:1B51.0002/input/input5
[    2.872142] input: Corsair CORSAIR DARK CORE RGB SE Wireless USB Receiver Consumer Control as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-6/1-6:1.0/0003:1B1C:1B51.0002/input/input6
[    2.926733] input: Corsair CORSAIR DARK CORE RGB SE Wireless USB Receiver as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-6/1-6:1.0/0003:1B1C:1B51.0002/input/input7
[    2.926750] input: Corsair CORSAIR DARK CORE RGB SE Wireless USB Receiver as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-6/1-6:1.0/0003:1B1C:1B51.0002/input/input8
[    2.926767] input: Corsair CORSAIR DARK CORE RGB SE Wireless USB Receiver as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-6/1-6:1.0/0003:1B1C:1B51.0002/input/input9
[    2.926784] input: Corsair CORSAIR DARK CORE RGB SE Wireless USB Receiver Keyboard as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-6/1-6:1.0/0003:1B1C:1B51.0002/input/input10
[    2.926849] hid-generic 0003:1B1C:1B51.0002: input,hiddev1,hidraw1: USB HID v1.11 Mouse [Corsair CORSAIR DARK CORE RGB SE Wireless USB Receiver] on usb-0000:02:00.0-6/input0
[    2.936066] hid-generic 0003:1B1C:1B51.0003: hiddev2,hidraw2: USB HID v1.11 Device [Corsair CORSAIR DARK CORE RGB SE Wireless USB Receiver] on usb-0000:02:00.0-6/input1
[    3.026159] input: Logitech Logitech BT Mini-Receiver as /devices/pci0000:00/0000:00:07.1/0000:0a:00.3/usb3/3-2/3-2.2/3-2.2:1.0/0003:046D:C70E.0004/input/input11
[    3.080513] hid-generic 0003:046D:C70E.0004: input,hidraw3: USB HID v1.11 Keyboard [Logitech Logitech BT Mini-Receiver] on usb-0000:0a:00.3-2.2/input0
[    3.163373] usb 3-2.3: new full-speed USB device number 4 using xhci_hcd
[    3.297522] usb 3-2.3: New USB device found, idVendor=046d, idProduct=c70a, bcdDevice=40.02
[    3.297524] usb 3-2.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.297525] usb 3-2.3: Product: Logitech BT Mini-Receiver
[    3.297526] usb 3-2.3: Manufacturer: Logitech
[    3.297527] usb 3-2.3: SerialNumber: 000761A35EDF
[    3.558937] input: Logitech Logitech BT Mini-Receiver Mouse as /devices/pci0000:00/0000:00:07.1/0000:0a:00.3/usb3/3-2/3-2.3/3-2.3:1.0/0003:046D:C70A.0005/input/input22
[    3.559046] input: Logitech Logitech BT Mini-Receiver Consumer Control as /devices/pci0000:00/0000:00:07.1/0000:0a:00.3/usb3/3-2/3-2.3/3-2.3:1.0/0003:046D:C70A.0005/input/input23
[    3.613428] input: Logitech Logitech BT Mini-Receiver System Control as /devices/pci0000:00/0000:00:07.1/0000:0a:00.3/usb3/3-2/3-2.3/3-2.3:1.0/0003:046D:C70A.0005/input/input24
[    3.613490] hid-generic 0003:046D:C70A.0005: input,hiddev3,hidraw4: USB HID v1.11 Mouse [Logitech Logitech BT Mini-Receiver] on usb-0000:0a:00.3-2.3/input0
[    4.092988] usbcore: registered new interface driver snd-usb-audio</code>
====================================================================================================================================
[olivier@thorielle ~]$ inxi -xxx --usb
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 10 rev: 2.0 speed: 480 Mb/s 
           chip ID: 1d6b:0002 
           Device-1: 1-2:2 info: SteelSeries ApS type: Audio,HID 
           driver: hid-generic,snd-usb-audio,usbhid interfaces: 6 rev: 1.1 speed: 12 Mb/s 
           chip ID: 1038:12ad 
           Device-2: 1-6:3 info: Corsair type: Mouse,HID driver: hid-generic,usbhid 
           interfaces: 2 rev: 2.0 speed: 12 Mb/s chip ID: 1b1c:1b51 
           serial: 16007025AF099D2258CCD846F5001946 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.1 speed: 10 Gb/s 
           chip ID: 1d6b:0003 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 4 rev: 2.0 speed: 480 Mb/s 
           chip ID: 1d6b:0002 
           Hub: 3-2:2 info: Logitech C-UV35 [Bluetooth Mini-Receiver] (HID proxy mode) 
           ports: 3 rev: 2.0 speed: 12 Mb/s chip ID: 046d:0b02 
           Device-3: 3-2.2:3 info: Logitech MX1000 Bluetooth Laser Mouse type: Keyboard 
           driver: hid-generic,usbhid interfaces: 1 rev: 2.0 speed: 12 Mb/s 
           chip ID: 046d:c70e serial: 000761A35EDF 
           Device-4: 3-2.3:4 info: Logitech MX5000 Cordless Desktop type: Mouse 
           driver: hid-generic,usbhid interfaces: 1 rev: 2.0 speed: 12 Mb/s 
           chip ID: 046d:c70a serial: 000761A35EDF 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.0 speed: 5 Gb/s 
           chip ID: 1d6b:0003 
[olivier@thorielle ~]$ </code>

Hope that can help you.

**Comment by Sapd** [comment]
Your device has an other id. You could try changing `idProduct` in `HeadsetControl/src/devices/steelseries_arctis7.c` line 15 to 0x12ad

Recompile and try again then.

**Comment by olielvewen** [comment]
I've created another package and updated this one was installed thanks the help of French Manjaro forum. 
It will be nice if you could provide a list of products which are supported and not.
Well now my headset is reconized however none features are supported. 
`
# Casque non branché
[olivier@luthien ~]$ HeadsetControl -b
No supported headset found
# Casque branché
[olivier@luthien ~]$ HeadsetControl -b
Found SteelSeries Arctis 7!

Couldn't open device.
# Fonctionnalité non supporté par ce modèle de casque
[olivier@luthien ~]$ sudo HeadsetControl -b
[sudo] Mot de passe de olivier : 
Found SteelSeries Arctis 7!

Error: This headset doesn't support battery status
[olivier@luthien ~]$ 

 `
BTW. As you can see, We get the same output if the device is connected or not.

**Comment by Sapd** [comment]
Ah I didn't see that you want to query the battery.
Battery is currently only supported by the Corsair void (pro) as stated under _Other Features_ in the readme

**Comment by jamesj999** [comment]
This issue should now be able to be closed. HeadsetControl now supports the 2019 variant of this headset and has battery support for both variants.

**Comment by olielvewen** [comment]
Yes. You have reason.
