### ISSUE TITLE
HS70 Support?

### ISSUE THREAD

**Issue by TacoRaptor67** [Sapd/HeadsetControl#36]
I noticed the Void is supported, so I was wondering.. any chance of the Corsair HS70 being supported? With what I've found this program is my only chance for getting sidetone from this headset on Linux. If it isn't possible I understand, but I thought I'd ask. I personally have little to no experience with Linux otherwise I'd be happy to help with adding support myself.

**Comment by Sapd** [comment]
There could be a chance that Corsair uses the same protocol for all their headsets. So you could try opening `src/devices/corsair_voidpro.c` replacing the productid with the of the HS70, recompile and test.

**Comment by JMmontilla** [comment]
I just bought an HS70, it would be awesome to add support for it :) (I would like to try the solution proposed by Sapd, but i have no idea about that recompiling thing xd, any help with that?)

**Comment by Sapd** [comment]
See https://github.com/Sapd/HeadsetControl/wiki/Adding-a-Corsair-device (it could work)

**Comment by olback** [comment]
@TacoRaptor67 @JMmontilla I can upload a version that you can test your HS70 with if you post the output of `lsusb`.

**Comment by podiki** [comment]
This works with commit d601fb0 as they have the same device id (I have an HS70). I can fetch the battery level but haven't tried anything else (not sure there is anything else for this headset).

Only thing is that HS70 is missing in the udev rules.

**Comment by naag** [comment]
I just tried setting the sidetone level and that works as well as setting the light on / off. By now also the udev rules have been updated, so I just copied those to `/etc/udev/rules.d/` and all is good now.

Just noticed that I have to reactivate the sidetone level after muting & unmuting the mic.

**Comment by Sapd** [comment]
fixed in https://github.com/Sapd/HeadsetControl/pull/105
