### ISSUE TITLE
GUI for HeadsetControl

### ISSUE THREAD

**Issue by nicola02nb** [Sapd/HeadsetControl#365]
Hi @Sapd,
in last months I developed a GUI for HeadsetControl, do you want to [give it a look](https://github.com/nicola02nb/HeadsetControl-GUI) and maybe add to your readme as a third party program/script?

**Comment by Sapd** [comment]
Hello,

feel free to create a PR for including it

**Comment by nicola02nb** [comment]
It's actually a separate program that uses the exe from your gh release.
It's a total different project take a look there: [https://github.com/nicola02nb/HeadsetControl-GUI](https://github.com/nicola02nb/HeadsetControl-GUI)

**Comment by Sapd** [comment]
Yep, I already took a deep look, nice work :)

My answer refers to the readme, you can simply create a PR here to link your project in the readme

**Comment by nicola02nb** [comment]
Oh, ok...  sorry for misunderstanding
