### ISSUE TITLE
cannot install it

### ISSUE THREAD

**Issue by Joel-Costamagna** [Sapd/HeadsetControl#4]
on debian jessie with kde, i have problems with the libusb : 
```
gcc main.c -std=gnu99 -L"/usr/lib" -lusb-1.0 -o headsetcontrol
main.c:21:31: fatal error: libusb-1.0/libusb.h: no such  file or folder
 #include <libusb-1.0/libusb.h>
```
i tried installing libusb 1.0 with aptitude, but it didn't solve the problem

can you help me ?
thanks

**Comment by parkerlreed** [comment]
That should just be your normal libusb install. What does this return?

````
ls /usr/lib/pkgconfig/libusb-*
````

**Comment by Joel-Costamagna** [comment]
ok thanks it worked, i didn't have the dev version installed
