### ISSUE TITLE
Corsair Corsair VOID RGB USB Gaming Headset

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [Sapd/HeadsetControl#45]
Can you please add support for Corsair Corsair VOID RGB USB Gaming Headset? It's device ID is: 1b1c:1b2a 

Thanks in advance.

**Comment by Sapd** [comment]
Download the project, open `src/devices/corsair_void.c` and add `0x1b2a` to the array in line 19. Then compile like stated in the README and test.

If you confirm that it is successful for you, we can include it into the project.

**Comment by KrDimitrov** [comment]
You can add that udev file to the udev folder of the project and then make a pull request!

**Comment by KrDimitrov** [comment]
Well, yes. You should fork the repo, make a branch and then commit your changes. Then you submit a pull request. I suggest you read about contributing on github. There are some good guides out there.

**Comment by Sapd** [comment]
Yep thanks, I merged https://github.com/Sapd/HeadsetControl/pull/46
