### ISSUE TITLE
Corsair Void Wired Not supported

### ISSUE THREAD

**Issue by jaypey** [Sapd/HeadsetControl#47]
In your readme you said that my headset(Corsair Void Wired) was supported but when using your program I get "No supported headset found". Is there a fix for that error?

**Comment by Sapd** [comment]
You got some revision, which was not tested yet.

1. Find out your deviceid, e.g. with the command `lsusb`
2. Open `src/devices/corsair_void.c` and add it to the array in line 19
3. Compile like stated in the README and test
4. Report back if it was successful, so we can add it in the repository (or create a pull request)

**Comment by Sapd** [comment]
https://github.com/Sapd/HeadsetControl/pull/48
