### ISSUE TITLE
Rename executable to headsetcontrol

### ISSUE THREAD

**Issue by gort818** [Sapd/HeadsetControl#52]
I think the executable should be in all lowercase, almost all binaries in *nix systems are lowercase..

I would make it a lot easier to call in Linux since the file systems are mostly case sensitive.

**Comment by Sapd** [comment]
A convention doesn't really exist (some non-gnu binaries also have camel-case, NetworkManager is a good example). On the other hand, I didn't really think about it.
So it could actually be changed, if an update has no major impact.

**Comment by Sapd** [comment]
Will be done in PR https://github.com/Sapd/HeadsetControl/pull/61. Since the big changes there are a good opportunity for such a change.
