### ISSUE TITLE
save settings?

### ISSUE THREAD

**Issue by ProfessorStrawberry** [Sapd/HeadsetControl#54]
Hi! I love your project. I just would love to save the settings permanently. Is there a way to achieve that? I am using Arch with KDE.

**Comment by parkerlreed** [comment]
If you setup udev to allow your user access, you could add the command to the session startup to apply it.

**Comment by ProfessorStrawberry** [comment]
I am still a beginner, but I guess I should be able to do that. Thank you

Oh btw.: is it possible to turn of LED, but keep the microphone LED on, when muted. This is the default behavior on the corsair void pro.

Have a good one!

**Comment by Sapd** [comment]
> Oh btw.: is it possible to turn of LED, but keep the microphone LED on, when muted. This is the default behavior on the corsair void pro.
> 
> Have a good one!

In theory yes, but it needs further analysing of the protocol to understand how the LED exactly behave (by someone with a corsair headset)

**Comment by Sapd** [comment]
I'm closing the issue because it is not something which can be implemented in this repository. But feel free to continue the discussion/question
