### ISSUE TITLE
Corsair virtuoso

### ISSUE THREAD

**Issue by IceCupe123** [Sapd/HeadsetControl#71]
cant get the corsair virtuoso to work added it like the other corsair headsets

**Comment by nkconnor** [comment]
I downloaded the iCUE software on my Macbook but it seems broken. Also some complaints from other users on the Corsair forums the past month about this. If anybody has a Windows PC, that would be helpful..

**Comment by Sapd** [comment]
I need more information, like what OS you have, what you have tried (with sudo/without etc.), and what is the error message.

However it could be, that the virtuso has a different protocol. That would mean that it's protocol also has to be analyzed, like with the other devies.

**Comment by nkconnor** [comment]
@Sapd I'm running Ubuntu 18.04. I added the Virutoso device to `corsair_void.c` following the Wiki instructions. Using `sudo`, I can get most of the commands to return:

```
Found Corsair Void (Pro)!

Success!
```

The battery level command hangs indefinitely. No commands have any observable effect on the headset, so I figured probably different protocol.

Curiously, the device ID changed between when I looked at it yesterday and today (it has been unplugged/replugged into USB).

The iCUE software doesn't work on my Mac... so I'm not sure how to move forward with this.

**Comment by nkconnor** [comment]
@Sapd I managed to get iCUE working when connected directly to the headset over USB. However, I'm having trouble making sense of the USB traffic and finding the pattern we need.

Using wireshark,

There's two URB CONTROL packets of length 40(submit) and 34(complete) that get sent out to the device everytime sidetone changes. But nothing changes between the packets except for the IO ID.

There's a lot of passive background traffic with byte lengths 32, 88, 288, and 96, but I can't really tell if these are related to the sidetone or not. 

The 96 packet has 64 bytes of 'leftover capture data' which matches the message size I think you are sending with `hid_send_feature_report`. But it says URB_INTERRUPT (completed) and matches a request with length 32.

I'm not sure how to go any further here. Any tips for me?

**Comment by Sapd** [comment]
@nkconnor When I tried it in the past with Wireshark I had the issue of not seeing the packet payload. You have probably the same problem.
Try it with usblyzer https://github.com/Sapd/HeadsetControl/wiki/Development

I think would have to look again into getting capturing working with wireshark and writing a wiki entry some time. There are probably scripts for capturing HID devices.

**Comment by nkconnor** [comment]
I think usblyzer only supports Windows

**Comment by Sapd** [comment]
Right, I forgot about that.

Okay, I just tried it again in Wireshark and it was no problem at all (probably because I have much more experience now than when I first wrote the software).
However I did it in a windows VM, as I didn't want to disable SIP for Wireshark on my Mac.

<img width="1082" alt="corsair-sidetone-04-00" src="https://user-images.githubusercontent.com/671752/79334699-13240f00-7f21-11ea-9ad5-0455ad3e9de3.png">
<img width="1070" alt="corsair-sidetone-04-f4" src="https://user-images.githubusercontent.com/671752/79334709-17502c80-7f21-11ea-996c-84adb58c33c8.png">

When you look in the data, you can clearly see some change. 

If you don't see any value change, make sure the sidetone actually changes (so don't keep your headset just on the table). Because I noticed the same problem, and then also noticed that the headset simply bugged.

For filtering I used these arguments
`usb.bInterfaceClass == HID && usb.endpoint_address.direction != IN && usb.src == host && usb.setup.wLength == 64`
Note that I added a length, as I noticed that a lot of keep-alive (or some other noise) packages were sent with a different length.

You can also see, that the data in the image is highly similar to the implementation in corsair_void.c:
`unsigned char data[64] = { 0xFF, 0x0B, 0, 0xFF, 0x04, 0x0E, 0xFF, 0x05, 0x01, 0x04, 0x00, num, 0, 0, 0, 0 };`
(Just the 6-th byte, counting from 0, is in my capture a 0x01 instead of 0xFF is different. Probably software update or some feature activated?)

**Comment by nkconnor** [comment]
Thanks for getting this far in here. Very strange, I get really good info from Wireshark when I turn sidetone or other features on/off, but really can't see anything meaningful when adjusting the value/slider.

Possibly SIP or something else I'm doing is interfering..

**Comment by Sapd** [comment]
> Thanks for getting this far in here. Very strange, I get really good info from Wireshark when I turn sidetone or other features on/off, but really can't see anything meaningful when adjusting the value/slider.
> 
> Possibly SIP or something else I'm doing is interfering..

Did you see a SET_REPORT packet with length 100 (decimal; 64 in hex)?
Also try the mute button. I noticed when trying to mute/unmute, it will send the sidetone packet first, too (for some reason with sidetone set when mute activated, and unset/set 0 if unmuted).

**Comment by nkconnor** [comment]
I think maybe found the issue. All recorded traffic has `usb.dst == "host"`.. there is no recorded traffic with `usb.src == "host"` (like your filter shows)

**Comment by Sapd** [comment]
The Wireshark wiki says, that you have to deactivate SIP if you have Catalina. Probably it's this.
Otherwise I guess you'll have to use Virtualbox or some other VM solution for capturing.

**Comment by themoosman** [comment]
I have this headset and a working test Win VM.  How can I be of assistance?

**Comment by Sapd** [comment]
@themoosman You can find a tutorial here https://github.com/Sapd/HeadsetControl/wiki/Development

**Comment by joseant79** [comment]
I have a Virtuoso too, this is what I was able to get
Side-tone full up:
![Screenshot_20200508_183221](https://user-images.githubusercontent.com/17211824/81458927-59ecd980-915a-11ea-9190-e2d6eaa9b2cd.png)

Side-tone all the way down: 

![Screenshot_20200508_183414](https://user-images.githubusercontent.com/17211824/81458959-8c96d200-915a-11ea-89d6-f9f696635bf7.png)

**Comment by Sapd** [comment]
Try to select only the HID-devices on the left side.

Usually it should be a report. So check those packets, too.

**Comment by joseant79** [comment]
Alsamixer is able to control the sidetone correctly on the Virtuoso, the same way as the iCue software does, now the only thing that I am interested  is in check the remaining battery

**Comment by joseant79** [comment]
BTW, I tried selecting only the HID devices and still showing nothing, don't know if I am doing something wrong

**Comment by nfaggian** [comment]
@joseant79 : what does your alsamixer output look like?

**Comment by nkconnor** [comment]
Forgot to subscribe here. Also curious how you are able to get this to work in alsamixer @joseant79

**Comment by nkconnor** [comment]
![Screenshot from 2020-07-06 10-02-59](https://user-images.githubusercontent.com/6473809/86607821-bfe9b780-bf77-11ea-8175-f47dfc460189.png)

It works for me, too! I had to make sure the multi-channel input selection was made and then adjust the first 'Headset' in alsa. There's a patch to rename that to 'Sidetone' pending I think.

**Comment by vuurvoske** [comment]
Hi, i just came here to tell that i have my virtuoso se working on ubuntu 20.04 out of the box. Issues i noticed:
- low volume (in comparisement to windows 10), firefox (youtube) however is extremely loud in comparisement
- very annoying sidetone.
- The slightest thing triggers the headset to enable again.

**Comment by nkconnor** [comment]
@vuurvoske you probably have multiple volume channels causing the volume discrepancy. Check Ubuntu sound settings

**Comment by joseant79** [comment]
![Screenshot_20200708_172659](https://user-images.githubusercontent.com/17211824/86980146-55d03e80-c140-11ea-9334-d0bc9b0def64.png)

It was working well out of the box, just cranked the sidetone up and then press the mic button for 5 seconds and voila!

**Comment by nfaggian** [comment]
Anyone had any luck with these headphones and turning off the LED's in linux?

**Comment by iommu** [comment]
Ok looking at the wireshark data it seems like the data is quite weird having the first 2 and last 2 bytes swapped as well as having a truncated 0x1XXXX as the 5th byte when the value is 100% so it starts at 0x10400 and goes down to 0xd600 represented at 0x0004 and 0x00d6 respectively. 

However as others have shown the sidetone does work in alasmixer and as such the alsa implementation code is mirrored on github [here](https://github.com/torvalds/linux/blob/c9c9735c46f589b9877b7fc00c89ef1b61a31e18/sound/usb/mixer_maps.c#L357) so it might be easier to reconsturct the alsa code that deconstruct the iCUE USB stream

**Comment by hmajid2301** [comment]
Any way to get the battery level in Ubuntu ?

**Comment by AR2000AR** [comment]
> @Sapd I'm running Ubuntu 18.04. I added the Virutoso device to `corsair_void.c` following the Wiki instructions. Using `sudo`, I can get most of the commands to return:
> 
> ```
> Found Corsair Void (Pro)!
> 
> Success!
> ```
> 
> The battery level command hangs indefinitely. No commands have any observable effect on the headset, so I figured probably different protocol.
> 
> Curiously, the device ID changed between when I looked at it yesterday and today. Possibly this is due to a firmware update from messing around with the iCUE mac software. The iCUE software barely works, so I'm not sure how to move forward with this in absence of a PC.

In my case the command `headsetcontrol -b` return `Battery: Unavailable` when I change the volume form the headset.

**Comment by RichardsonWTR** [comment]
Does this help? https://github.com/ckb-next/ckb-next/issues/785

**Comment by Sapd** [comment]
> Does this help? [ckb-next/ckb-next#785](https://github.com/ckb-next/ckb-next/issues/785)

The report itself not. Someone needs to take a look at it with WireShark https://github.com/Sapd/HeadsetControl/wiki/Development#adding-a-new-headset
for turning off LED or getting the Battery level.
(Sidetone can not be supported as outlined some posts above, as it is controlled by an audio/volume channel).

**Comment by Patola** [comment]
So the Corsair Virtuoso support is not yet done on this application? I'd have to edit the source code to get it working?

For some reason pipewire did not show the 'sidetone' slider here. What should I do for it to show?

**Comment by jayofdoom** [comment]
Yeah, as far as I'm aware this headset is still not working wirelessly on Linux.

**Comment by Patola** [comment]
Thanks, @jayofdoom. Just a slight correction on your wording, the headset settings (sidetone, RGB settings) still are not working wirelessly on Linux, but the headset works fine otherwise -- you just can't adjust anything other than the volume.

**Comment by jayofdoom** [comment]
Even with the wireless dongle? I didn't realize that had been fixed. I'll try to make it work. I thought it had to be directly connected with a cable.

On Sep 19, 2022 4:20 PM, Patola ***@***.***> wrote:

Thanks, @jayofdoom<https://github.com/jayofdoom>. Just a slight correction on your wording, the headset settings (sidetone, RGB settings) still are not working wirelessly on Linux, but the headset works fine otherwise -- you just can't adjust anything other than the volume.

**Comment by Patola** [comment]
Yes, even with the wireless dongle.

**Comment by AR2000AR** [comment]
Using it wirelessly too. Never had any issue (debian 10,11 and popos)

**Comment by Sapd** [comment]
Closing, the sidetone is controlled via an audio channel for Virtuso, which we can't access via HID.
However feel free to open another issue for other features like battery.
