### ISSUE TITLE
Couldn't open device.

### ISSUE THREAD

**Issue by KannstGarnichts** [Sapd/HeadsetControl#73]
~/HeadsetControl/build$ ./headsetcontrol -s 16
Found Logitech G633/G933/G935!

Couldn't open device.

Any solutions?

**Comment by Sapd** [comment]
Probably no permissions. Use sudo or install the respective udev rules by typing `make install` as stated in the README.

**Comment by hosler** [comment]
I needed to add my VOID product id to the udev rules: 0a1a

# My VOID
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1b1c", ATTRS{idProduct}=="0a1a", TAG+="uaccess"

**Comment by matzedings** [comment]
Can confirm that permissions are not working even with `sudo make install`, I still need to use sudo.

If this is really due to udev rules, could you implement this into your code?

**Comment by morhook** [comment]
Had same issue as reporter! Fixed the same way. Thanks a lot! (I think we should close this issue)
