### ISSUE TITLE
Arctis 1

### ISSUE THREAD

**Issue by Jabrwock** [Sapd/HeadsetControl#74]
Arctis 1, Ubuntu 18.04
Bus 001 Device 012: ID 1038:12b3 SteelSeries ApS

I tried adding 0x12b3 to steelseries_arctis.c, but I get

Requested/supported HID device not found or system error. 

I will take a look at https://github.com/Sapd/HeadsetControl/wiki/Development and see what I can contribute.

**Comment by Sapd** [comment]
Did you try it with sudo?

Otherwise, could be that device_arctis.idInterface is not correct for you in steelseries_arctis.c on line 24

**Comment by piozylka** [comment]
bump

**Comment by hadess** [comment]
Seems to have been fixed by: https://github.com/Sapd/HeadsetControl/pull/98
