### ISSUE TITLE
Gentoo ebuild

### ISSUE THREAD

**Issue by SabbathHex** [Sapd/HeadsetControl#82]
I wrote a Gentoo ebuild for headsetcontrol. Since there is no installation section in the repo - should I add it as a wiki page?

**Comment by Sapd** [comment]
Yes, if it is not a one/two liner, you can add it there; and then link it via the Building section - with the info that it it possible to use ebuild instead of building yourself

**Comment by SabbathHex** [comment]
Thanks for the reply. The ebuild applies a patch to the udev rules location and reloads the udev rules after the package is installed. 

Looks like the wiki is closed for editing:
![image](https://user-images.githubusercontent.com/9886026/80748228-71ccb980-8ad9-11ea-969e-9ced5af44a9f.png)

For an editable wiki:
![image](https://user-images.githubusercontent.com/9886026/80748252-7a24f480-8ad9-11ea-9242-f0f0f1511147.png)

**Comment by Sapd** [comment]
Ahh, try again, I changed the permissions.

**Comment by SabbathHex** [comment]
Works, thanks! I'll submit the PR
![image](https://user-images.githubusercontent.com/9886026/80754123-5b2b6000-8ae3-11ea-9db9-2fd17bfd9398.png)
