### ISSUE TITLE
Arch Linux AUR Package

### ISSUE THREAD

**Issue by sehnem** [Sapd/HeadsetControl#86]
Hey, congratulations for the great work!

Just came here to inform that I created and AUR package for this repository [headsetcontrol-git](https://aur.archlinux.org/packages/headsetcontrol-git/). Anyone using Arch based distributions have an easier way to install it now.

**Comment by Sapd** [comment]
Thank you :)

Just out of curiosity, what is the difference between the package you created and https://aur.archlinux.org/packages/headsetcontrol ?

**Comment by sehnem** [comment]
Ohh, there was a package? sorry, I did not see in the readme and duplicated it, I think it is the same package.

**Comment by parkerlreed** [comment]
Technically yours was more correct. git packages need to have -git on them. Regular are for pointy releases.

https://wiki.archlinux.org/index.php/VCS_package_guidelines
