### ISSUE TITLE
Logitech G933 - can't disable LED when connected with USB cable

### ISSUE THREAD

**Issue by Ginden** [Sapd/HeadsetControl#89]
**USB cable connected**:
`sudo headsetcontrol -c -l 1` - enables LED properly.
`sudo headsetcontrol -c -l 0` - doesn't disable LED.

**USB cable disconnected**:
`sudo headsetcontrol -c -l 1` - enables LED properly.
`sudo headsetcontrol -c -l 0` - disable only strip (same as #65)

**Comment by KrDimitrov** [comment]
Works fine on windows. I noticed when off they turn on for a **brief** time when the usb cable is connected, but turning then on and off works fine.

**Comment by fr33-man** [comment]
Are you using analog or digital output?
If you switch to analog, does it still happen?

**Comment by Ginden** [comment]
After updating Ubuntu to 20.04 and updating HeadsetControl from `23bf9d9` to  `7557695` everything works properly.
