### ISSUE TITLE
Logitech G930 on MacOS

### ISSUE THREAD

**Issue by decluga** [Sapd/HeadsetControl#9]
After installing libusb (btw: now it has version 1.0.21) and cloning repo I typed:
`gcc main.c -L"/usr/local/Cellar/libusb/1.0.21/lib" -lusb-1.0 -I"/usr/local/Cellar/libusb/1.0.21/include" -std=gnu99 -o headsetcontrol` and had no errors, than I tried to use and had: `HeadsetControl: command not found`

**Comment by Sapd** [comment]
How did you start it? If the binary is in the current terminal folder you have to start it like this: `./headsetcontrol 128`

**Comment by decluga** [comment]
Thanks, it helps. Seems I need to make alias for that.
