### ISSUE TITLE
Notification daemon

### ISSUE THREAD

**Issue by Manawyrm** [Sapd/HeadsetControl#92]
Hi! 

![screenshot](https://screenshot.tbspace.de/jpcefkgwhvy.png)

Thank you very very much for this useful piece of software. 
I wrote a small (and pretty ugly) daemon that will display notifications for the battery state of your devices: 
https://github.com/Manawyrm/headsetcontrol-notificationd

Should we link to this repo in the README for HeadsetControl? 
I'm probably not the only user that would like to have desktop notifications for battery status. 

Thanks!

**Comment by centic9** [comment]
In the same vein, if you add a "related tools" section there is another tool based on HeadsetControl: 

I wrote a small app-indicator which displays the current battery percentage and provides a menu to control features of the headset (lights, sidetone, ...). It uses HeadsetControl to do the actual communication with the headset

It's available at https://github.com/centic9/headset-charge-indicator/


![Bildschirmfoto von 2020-05-23 10-25-57](https://user-images.githubusercontent.com/548322/82725816-004ee800-9ce0-11ea-9d15-aa404c6ee85b.png)

**Comment by Sapd** [comment]
Sure, look here https://github.com/Sapd/HeadsetControl/pull/93/files

Does the description suit you both?

**Comment by Manawyrm** [comment]
Cool, fine by me :)

**Comment by Manawyrm** [comment]
Just a small nitpick: 
There's a typo in the Readme, it says "headsetcontrol-notifcationid" instead of "headsetcontrol-notifcationd". 
Should I send a PR to fix that or do you want to just change it?

**Comment by Sapd** [comment]
I quickly fixed it
