### ISSUE TITLE
Corsair Corsair VOID PRO Wireless missing in udev rules

### ISSUE THREAD

**Issue by simonoesterle** [Sapd/HeadsetControl#96]
HeadsetControl is unable to open the Corsair VOID PRO Wireless due to the following line 
missing in 70-headsets.rules
`# Corsair VOID PRO Wireless`
`KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1b1c", ATTRS{idProduct}=="0a1a", TAG+="uaccess"`

lsusb output for the Corsair VOID PRO Wireless on my system is:
`Bus 005 Device 002: ID 1b1c:0a1a Corsair Corsair VOID PRO Wireless Gaming Headset`

**Comment by linuxkd** [comment]
This is also true for me as well. The previously mentioned udev rule is not present, and has to be added manually.

```
➜ lsusb | grep Corsair
Bus 005 Device 008: ID 1b1c:0a1a Corsair
